### ISSUE TITLE
help

### ISSUE THREAD

**Issue by rafix8989** [Reinbert/ros_diffdrive_robot#3]
Hello, help with steering the rc car with the esc with the help of the steering wheel.
if you are interested I will describe the details

**Comment by Reinbert** [comment]
@rafix8989 What are you suggesting?

**Comment by rafix8989** [comment]
I need your help.
I have an rc car with esc and servo
rasbpery pi 4  and arduino need to convert joy.cpp file from ros to work with logitech G29, can you help?
To control this car via wifi from a laptop with logitech G29

**Comment by Reinbert** [comment]
Which joy.cpp file are you referring to? Because there is none in this repository.
