### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Gadiel99** [Reinbert/ros_diffdrive_robot#4]
Greetings, Instead of the micro controller that you used, I am using a Arduino UNO. So how can i set up my arduino to the DC motor in terms of coding?

**Comment by Reinbert** [comment]
Hey! 
I'm not sure if I understand your problem correctly, because "in terms of coding the Arduino to DC motor" part, that part stays roughly the same while everything else needs to change.

**Comment by Gadiel99** [comment]
It's ok I already figured it out thank you!
