### ISSUE TITLE
OnTwist Issue

### ISSUE THREAD

**Issue by kghodstinat** [Reinbert/ros_diffdrive_robot#5]
On this File ros_diffdrive_robot.ino
OnTwist call back:
These two variables are defined but never used:
float x = max(min(msg.linear.x, 1.0f), -1.0f);
float z = max(min(msg.angular.z, 1.0f), -1.0f);

Where are using these two variables?

**Comment by Reinbert** [comment]
You're right. Thank you for pointing that out. They're ought to be used in the next code block. I thought I fixed that already, but it may have been in another repo.

**Comment by Reinbert** [comment]
@kghodstinat I just fixed it in this commit: https://github.com/Reinbert/ros_diffdrive_robot/commit/a77a49c129a397110530007fb063b8c13b4d1eb6

Please close the issue if you think the problem is resolved now.

**Comment by kghodstinat** [comment]
@Reinbert, Perfect. Thanks for the commit.

**Comment by kghodstinat** [comment]
Issue Fixed.
